################################# Default configuration ###################
baseURL = "http://iocoaching.co.uk"
title = " Turkish Psychologist in London"
profile = ''
theme = "airspace-hugo"


defaultContentLanguage = "tr"
LanguageCode = "tr"


# post pagination
paginate = "4"
# post excerpt
summaryLength = "30"
# disqus short name
disqusShortname = "" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = []


#################################### Plugins ##############################

# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.css]]
link = "css/site.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"


############################### widgets #################################

[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


############################## navigation ###############################

# main menu
[[menu.main]]
name = "about"
URL = "about"
weight = 1

[[menu.main]]
weight = 2
name = "services"
hasChildren = true

  [[menu.main]]
      parent = "services"
      name = "individual_counselling"
      URL = "individual-counselling"
      weight = 1

  [[menu.main]]
      parent = "services"
      name = "child_counseling"
      URL = "child-counseling"
      weight = 2

  [[menu.main]]
      parent = "services"
      name = "adolescent"
      URL = "adolescent-psychology"
      weight = 3


[[menu.main]]
name = "fees"
URL = "fees"
weight = 3

[[menu.main]]
name = "blog"
URL = "blog"
weight = 4

[[menu.main]]
name = "contact"
URL = "contact"
weight = 6


# footer menu
[[menu.footer]]
name = "about"
URL = "about"
weight = 1

[[menu.footer]]
name = "blog"
URL = "blog"
weight = 3

[[menu.footer]]
name = "Fees"
URL = "fees"
weight = 4

[[menu.footer]]
name = "Contact"
URL = "contact"
weight = 6


#################### default parameters ################################
[params]
logo = "images/logo.png"
# Meta data
description = "This is meta description"
author = "Irem Ozkol - IOCoaching"
# Contact Information
mobile = "+44 744 7752169"
email = "info@iocoaching.co.uk"
location = "Holly Park Rd, London N11 3HB"
# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io
# Google Analitycs
google_analitycs_id = "UA-171529951-1" # Your ID# search
# multi-author support (if set to true, you must use an Array in the author field)
multi_author = false
domain='http://iocoaching.co.uk'
meta_keywords_tr="Türkçe Psikoterapi, terapi Londra, Uzman Türk Psikolog Londra, Londra Türkce Terapi Danismanlik, Uzman Psikolog İrem Özkol ,Londra Ingiltere Turk Psikolog, Turkce Terapi, Bireysel Danışmanlık, Çocuk Terapisi, Ergen Terapisti"
meta_keywords_en="English Psychotherapy, Counseling, London, Therapy, MSc Clinical Child Psychology, London Turkish Psychologist, Child Psychology, Adolescent Psychology, Teenager, Individual Counselling"
title_prefix_tr = "Psikoterapi & Psikolojik Danışmanlık - IO Coaching |"
title_prefix_en = "Psychotherapy & Counselling - IO Coaching |"

# Preloader
[params.preloader]
enable = true
preloader = "" # use .png , .svg or .gif format

# Navigation get start button
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"

# google map
[params.gmap]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyAXIFL-z-Teoy50Nso-ZM-prvGdsFL2Vgo&libraries=places"
map_latitude = "51.5987676"
map_longitude = "-0.0669526"
map_marker = "images/marker.png"

  
############################# social site ########################

[[params.social]]
icon = "ion-social-instagram" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.instagram.com/io.coaching/"

[[params.social]]
icon = "ion-social-facebook" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/profile.php?id=100064159807119"

[[params.social]]
icon = "ion-social-linkedin" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.linkedin.com/in/iremozkol/"


[languages]
################################ Turkish Language ########################
    [Languages.tr]
        languageName = "Türkçe"
        languageCode = "tr-tr"
        flagURL = "flags/tr.png"
        contentDir = "content/turkish"
        weight = 1
        home = "Anasayfa"
        # copyright
        copyright = "IOCoaching | Tüm hakları saklıdır."


################################ English Language ########################
    [Languages.en]
        languageName = "English"
        languageCode = "en-gb"
        flagURL= "flags/en.png"
        contentDir = "content/english"
        weight = 2
        home = "Home"
        # copyright
        copyright = "Copyright IOCoaching All Rights Reserved"
